trigger:
- master

strategy:
  matrix:
    linux:
      operatingSystem: 'ubuntu-latest'
    mac:
      operatingSystem: 'macos-latest'

pool:
  vmImage: $(operatingSystem)

steps:
- script: echo running on the operating system $(operatingSystem)
  displayName: 'Run a one-line script'
